### PR TITLE
change code color and background-color showing in admonition note to distinguish code and normal text

### PR DESCRIPTION
**Pull request by genshen**

### CODE REVIEW

**Comment by alephpiece** [comment]
`:::tip`的样式需要修改吗？里面的代码块是纯黑的背景，在我的浏览器上看起来是这样的：
image

**Comment by genshen** [comment]
可以换下样式，这两种颜色在一块不是很协调

**Comment by genshen** [comment]
@alephpiece I have updated the code block theme. You can check it by switching ***Light/Dark*** mode on the top-right corner of page.

**Comment by alephpiece** [comment]
It looks great with dark mode. Could you make syntax highlighting in `:::note` blocks consistent with other blocks when enabling dark mode? I've just noticed that all of them were in the same dark style before this PR.

**Pull request merged**
